# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bulk_import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='data')),
            ],
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('product_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=300, null=True)),
                ('purchase_price', models.IntegerField(null=True)),
                ('sold_price', models.IntegerField(blank=True, null=True)),
                ('custodian', models.CharField(blank=True, max_length=100, null=True)),
                ('induction_date', models.DateField(auto_now_add=True)),
                ('sales_date', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('cust_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cust_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('cust_Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('profit', models.IntegerField(blank=True, null=True)),
                ('sold_by', models.CharField(blank=True, max_length=100, null=True)),
                ('prod_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('sales_status', models.CharField(blank=True, default='In Stock', max_length=25, null=True)),
            ],
        ),
    ]
